### ISSUE TITLE
Old version of `setuptools` in requirements

### ISSUE THREAD

**Issue by TimOliverMaier** [theGreatHerrLebert/proteolizard-algorithm#7]
Hey!

I am having pip resolve conflicts, because of the required version of `setuptools~=58.1.0`. 
Some packages in my local environment require `setuptools>=60.0.0` already. 

Is there a specific reason for using this `setuptools` version or can the requirements be updated?
It seems to me,  using `setuptools>=58.1.0` works, which would resolve the conflicts. 

see #8

**Comment by theGreatHerrLebert** [comment]
Yup, just used auto-generated requirements, this usually fixes the version number to the installed packages at that specific point in time. I will pull the changes and close! Thanks for spotting this.
